apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: open-cluster-management:work:agent
  namespace: open-cluster-management-agent
rules:
#- apiGroups: [""]
#  resources: ["configmaps", "secrets"]
#  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
#- apiGroups: ["coordination.k8s.io"] # lease for addon-xxx
#  resources: ["leases"]
#  verbs: ["get", "list", "watch"]
